name: Build VCoreOS - RapsiOS
on:
  push:
    branches:
      - '**'
    tags-ignore: 
      - '**'
  pull_request:
    types: [ opened, edited ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  raspiosbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt update; sudo apt install coreutils p7zip-full qemu-user-static zip 

      - name: Checkout CustomPiOS
        uses: actions/checkout@v2
        with:
          repository: 'guysoft/CustomPiOS'
          path: CustomPiOS
      
      - name: Checkout VCoreOS Project
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: repository
          submodules: true

      - name: Download Raspbian Source Image
        run: aria2c -d repository/src/image/ --seed-time=0 https://downloads.raspberrypi.org/raspios_lite_armhf_latest.torrent
      
      - name: Update CustomPiOS Paths
        run: cd repository/src && ../../CustomPiOS/src/update-custompios-paths

      - name: APT Cache
        uses: actions/cache@v2
        with:
          key: apt-cache
          path: ${{ github.workspace }}/repository/src/workspace/aptcache

      - name: Build Image
        run: sudo modprobe loop && cd repository/src && sudo bash -x ./build_dist

      - name: Copy output image
        if: github.event_name == 'schedule'
        run: cp ${{ github.workspace }}/repository/src/workspace/*-raspios-*-lite.img vcoreos-raspios-lite-latest.img
      
      - name: Compress the image
        if: github.event_name == 'schedule'
        run: zip vcoreos-raspios-lite-latest.zip vcoreos-raspios-lite-latest.img

      - uses: actions/upload-artifact@v1
        if: github.event_name == 'schedule'
        with:
          name: vcoreos-raspios-lite-latest.zip
          path: vcoreos-raspios-lite-latest.zip